version: "3.9" # optional since v1.27.0
services:
  mysql:
    #network_mode: "host"
    # net: host
    image: mysql:8
    container_name: mysql

    restart: always

    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: jobsInfo
      MYSQL_USER: root
    volumes:
      - .~/docker-conf/mysql/data:/docker-entrypoint-initdb.d/

  



    
    



